---
version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.${CPU_ARCHITECTURE}
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=django_user"
      - "POSTGRES_PASSWORD=django_password"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
