version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SENDGRID_API_KEY
      - "SENDGRID_FROM_EMAIL=calvin@redtail.consulting"
      - "DJANGO_SECRET_KEY=c%kkzpz0r9w58q^26cjnkd^a1+i84-u7u%ei39u6hc0&u^i0j3"
      - "DJANGO_DEBUG=True"
      - "DJANGO_ALLOWED_HOSTS=['localhost', '127.0.0.1', '*']"
      - "DATABASE_URL=postgres://postgres@db/postgres"
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
