# Generated by Django 4.0.10 on 2023-06-11 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('llm', models.CharField(choices=[('ChatGPT v3.5', 'ChatGPT v3.5'), ('ChatGPT v4', 'ChatGPT v4'), ('LLaMa', 'LLaMa')], default='ChatGPT v4', max_length=15)),
                ('persona', models.CharField(choices=[('Herbert', 'Herbert'), ('Jamie', 'Jamie'), ('Other', 'Other')], default='Other', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], default='user', max_length=4)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='saute.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
