# Generated by Django 4.1.5 on 2023-03-31 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Panorama",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hostname", models.CharField(max_length=255, unique=True)),
                (
                    "ipv4_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                (
                    "ipv6_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv6"
                    ),
                ),
                ("api_token", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="panorama_images"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("panorama_full", "Can read all Panorama instance details")
                ],
            },
        ),
        migrations.CreateModel(
            name="Prisma",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("tsg", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="prisma_images"),
                ),
            ],
            options={
                "permissions": [("prisma_full", "Can read all Prisma tenant details")],
            },
        ),
    ]
