# Generated by Django 4.1.5 on 2023-03-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("panosync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="panorama",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="panorama_images"),
        ),
        migrations.AddField(
            model_name="prisma",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="prisma_images"),
        ),
    ]
