name: Backend CI

on:
  push:
    branches:
      - main
      - development
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
  schedule:
    - cron: '0 8 * * *' # Run every day at 2am CST (which is 8am UTC)

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Code formatting with Black
        run: |
          pip install black
          black --check backend/

      - name: Linting with Flake8 and yamllint
        run: |
          pip install flake8 yamllint
          flake8 backend/ --exit-zero
          yamllint backend/

      - name: Run Django tests
        run: |
          cd backend
          python manage.py test

      - name: Build Docker images
        run: |
          docker-compose -f backend/docker-compose.yml build

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f backend/docker-compose.yml up -d

      - name: Check if web application is running
        run: |
          curl -s http://localhost:8000/ | grep "Django"
