# Generated by Django 4.0.10 on 2023-04-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ipv4_address', models.GenericIPAddressField()),
                ('ipv6_address', models.GenericIPAddressField()),
                ('api_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prisma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('tsg_id', models.CharField(max_length=100)),
            ],
        ),
    ]
